apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  labels:
    app: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: ecoroute/backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod

            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/ecoroute

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecoroute-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecoroute-secrets
                  key: POSTGRES_PASSWORD

            - name: AI_SERVICE_URL
              value: http://ai-service:8000

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"

            limits:
              memory: "1Gi"
              cpu: "500m"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 30
            periodSeconds: 15